#!/usr/bin/env node
'use strict';

// Generates docs/js/config.js with runtime settings for the static site.
// Reads CARTO_API_KEY from the environment (GitHub Actions secret) or from .env (local).

const { readFileSync, writeFileSync, existsSync } = require('fs');
const { join } = require('path');

const ROOT = join(__dirname, '..');
const ENV_PATH = join(ROOT, '.env');
const CONFIG_PATH = join(ROOT, 'docs', 'js', 'config.js');

function parseEnv(text) {
  const vars = {};
  for (const line of text.split('\n')) {
    const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);
    if (!match) continue;
    vars[match[1]] = match[2].replace(/^(['"])(.*)\1$/, '$2');
  }
  return vars;
}

function main() {
  const fileVars = existsSync(ENV_PATH) ? parseEnv(readFileSync(ENV_PATH, 'utf8')) : {};
  const cartoApiKey = process.env.CARTO_API_KEY || fileVars.CARTO_API_KEY || '';

  if (!cartoApiKey) {
    console.error('CARTO_API_KEY is not set (environment or .env)');
    process.exit(1);
  }

  const config = { cartoApiKey };
  writeFileSync(CONFIG_PATH, '// Generated by pipeline/write-config.js — do not edit or commit\n' +
    'window.APP_CONFIG = ' + JSON.stringify(config, null, 2) + ';\n');
  console.log('Wrote ' + CONFIG_PATH);
}

if (require.main === module) {
  main();
}

module.exports = { parseEnv };
